path = "C:/Users/chiara/Desktop/vgg predictor/results"
file_names=list.files(path = "C:/Users/chiara/Desktop/vgg predictor/results")

#labels
altro=c("lighter, light, igniter, ignitor",	"spotlight, spot","brass, memorial tablet, plaque","mousetrap")
abbigliamento= c("abaya",	"academic gown, academic robe, judge's robe",	"apron",	"bib",	"bikini, two-piece",	"brassiere, bra, bandeau",	"cardigan",	"cloak",	"clog, geta, patten, sabot",	"cowboy boot",	"fur coat",	"gown",	"hoopskirt, crinoline",	"jean, blue jean, denim",	"jersey, T-shirt, tee shirt",	"kimono",	"Loafer",	"maillot",	"maillot, tank suit",	"military uniform",	"miniskirt, mini",	"overskirt",	"pajama, pyjama, pj's, jammies",	"poncho",	"running shoe",	"sandal",	"sarong",	"sock",	"stole",	"suit, suit of clothes",	"sweatshirt",	"swimming trunks, bathing trunks",	"trench coat",	"velvet",	"vestment",	"wool, woolen, woollen",	"bolete")
accessori_veicoli=c("car mirror",	"car wheel",	"grille, radiator grille",	"odometer, hodometer, mileometer, milometer",	"oil filter",	"reel",	"seat belt, seatbelt")
accessori_persona=c("analog clock",	"backpack, back pack, knapsack, packsack, rucksack, haversack",	"bathing cap, swimming cap",	"bolo tie, bolo, bola tie, bola",	"bonnet, poke bonnet",	"bow tie, bow-tie, bowtie",	"buckle",	"cowboy hat, ten-gallon hat",	"crash helmet",	"digital clock",	"digital watch",	"feather boa, boa",	"hair slide",	"lipstick, lip rouge",	"mailbag, postbag",	"mask",	"mortarboard",	"necklace",	"perfume, essence",	"pickelhaube",	"purse",	"sombrero",	"sunglass",	"sunglasses, dark glasses, shades",	"wallet, billfold, notecase, pocketbook",	"wig","Windsor tie")
aerei=c("airliner",	"airship, dirigible",	"plane, carpenter's plane, woodworking plane",	"space shuttle",	"warplane, military plane",	"wing")
alimenti=c("confectionery, confectionary, candy store",	"drumstick",	"honeycomb",	"guacamole",	"consomme",	"hot pot, hotpot",	"trifle",	"ice cream, icecream",	"ice lolly, lolly, lollipop, popsicle",	"French loaf",	"bagel, beigel",	"pretzel",	"cheeseburger",	"hotdog, hot dog, red hot",	"mashed potato",	"head cabbage",	"broccoli",	"cauliflower",	"zucchini, courgette",	"spaghetti squash",	"acorn squash",	"butternut squash",	"cucumber, cuke",	"artichoke, globe artichoke",	"bell pepper",	"cardoon",	"mushroom",	"Granny Smith",	"strawberry",	"orange",	"lemon",	"fig",	"pineapple, ananas",	"banana",	"jackfruit, jak, jack",	"custard apple",	"pomegranate",	"hay",	"carbonara",	"chocolate sauce, chocolate syrup",	"dough",	"meat loaf, meatloaf",	"pizza, pizza pie",	"potpie",	"burrito",	"corn",	"acorn")
anfibi=c("European fire salamander, Salamandra salamandra",	"common newt, Triturus vulgaris",	"eft",	"spotted salamander, Ambystoma maculatum",	"axolotl, mud puppy, Ambystoma mexicanum",	"bullfrog, Rana catesbeiana",	"tree frog, tree-frog",	"tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui")
animali_estinti=c("triceratops",	"trilobite")
animali_marini=c("jellyfish",	"brain coral",	"dugong, Dugong dugon",	"sea lion")
animali_selvatici=c("three-toed sloth, ai, Bradypus tridactylus","Arabian camel, dromedary, Camelus dromedarius","llama","sorrel","tusker",	"echidna, spiny anteater, anteater",	"platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus",	"wallaby, brush kangaroo",	"koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus",	"wombat",	"timber wolf, grey wolf, gray wolf, Canis lupus",	"white wolf, Arctic wolf, Canis lupus tundrarum",	"red wolf, maned wolf, Canis rufus, Canis niger",	"coyote, prairie wolf, brush wolf, Canis latrans",	"dingo, warrigal, warragal, Canis dingo",	"dhole, Cuon alpinus",	"African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus",	"hyena, hyaena",	"red fox, Vulpes vulpes",	"kit fox, Vulpes macrotis",	"Arctic fox, white fox, Alopex lagopus",	"grey fox, gray fox, Urocyon cinereoargenteus",	"cougar, puma, catamount, mountain lion, painter, panther, Felis concolor",	"lynx, catamount",	"leopard, Panthera pardus",	"snow leopard, ounce, Panthera uncia",	"jaguar, panther, Panthera onca, Felis onca",	"lion, king of beasts, Panthera leo",	"tiger, Panthera tigris",	"cheetah, chetah, Acinonyx jubatus",	"brown bear, bruin, Ursus arctos",	"American black bear, black bear, Ursus americanus, Euarctos americanus",	"ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus",	"sloth bear, Melursus ursinus, Ursus ursinus",	"mongoose",	"meerkat, mierkat",	"wood rabbit, cottontail, cottontail rabbit",	"hare",	"Angora, Angora rabbit",	"zebra",	"hog, pig, grunter, squealer, Sus scrofa",	"wild boar, boar, Sus scrofa",	"warthog",	"hippopotamus, hippo, river horse, Hippopotamus amphibius",	"Madagascar cat, ring-tailed lemur, Lemur catta",	"indri, indris, Indri indri, Indri brevicaudatus",	"Indian elephant, Elephas maximus",	"African elephant, Loxodonta africana",	"lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens",	"giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca")
aracnidi=c("harvestman, daddy longlegs, Phalangium opilio",	"scorpion","tick","black and gold garden spider, Argiope aurantia",	"barn spider, Araneus cavaticus",	"garden spider, Aranea diademata",	"black widow, Latrodectus mactans",	"tarantula",	"wolf spider, hunting spider")
architetture=c("altar",	"beacon, lighthouse, beacon light, pharos",	"breakwater, groin, groyne, mole, bulwark, seawall, jetty",	"castle",	"cliff dwelling",	"dam, dike, dyke",	"dock, dockage, docking facility",	"dome",	"drilling platform, offshore rig",	"fountain",	"library",	"maze, labyrinth",	"megalith, megalithic structure",	"mobile home, manufactured home",	"obelisk",	"patio, terrace",	"pedestal, plinth, footstall",	"pier",	"stage",	"steel arch bridge",	"stupa, tope",	"sundial",	"suspension bridge",	"thatch, thatched roof",	"tile roof",	"totem pole",	"triumphal arch",	"viaduct",	"water tower",	"worm fence, snake fence, snake-rail fence, Virginia fence",	"wreck")
armi=c("assault rifle, assault gun",	"breastplate, aegis, egis",	"bullet train, bullet",	"cannon",	"chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour",	"cuirass",	"guillotine",	"holster",	"missile",	"projectile, missile",	"revolver, six-gun, six-shooter",	"rifle",	"scabbard",	"shield, buckler",	"tank, army tank, armored combat vehicle, armoured combat vehicle")
bevande=c("milk can",	"pop bottle, soda bottle",	"water bottle",	"whiskey jug",	"wine bottle",	"red wine",	"espresso",	"eggnog")
bovini=c("ox",	"bison",	"ram, tup",	"bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis",	"ibex, Capra ibex",	"hartebeest",	"impala, Aepyceros melampus",	"gazelle",	"water buffalo, water ox, Asiatic buffalo, Bubalus bubalis")
persone=c("ballplayer, baseball player","groom, bridegroom","scuba diver","pirate, pirate ship")
cani=c("Chihuahua",	"Japanese spaniel",	"Maltese dog, Maltese terrier, Maltese",	"Pekinese, Pekingese, Peke",	"Shih-Tzu",	"Blenheim spaniel",	"papillon",	"toy terrier",	"Rhodesian ridgeback",	"Afghan hound, Afghan",	"basset, basset hound",	"beagle",	"bloodhound, sleuthhound",	"bluetick",	"black-and-tan coonhound",	"Walker hound, Walker foxhound",	"English foxhound",	"redbone",	"borzoi, Russian wolfhound",	"Irish wolfhound",	"Italian greyhound",	"whippet",	"Ibizan hound, Ibizan Podenco",	"Norwegian elkhound, elkhound",	"otterhound, otter hound",	"Saluki, gazelle hound",	"Scottish deerhound, deerhound",	"Weimaraner",	"Staffordshire bullterrier, Staffordshire bull terrier",	"American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier",	"Bedlington terrier",	"Border terrier",	"Kerry blue terrier",	"Irish terrier",	"Norfolk terrier",	"Norwich terrier",	"Yorkshire terrier",	"wire-haired fox terrier",	"Lakeland terrier",	"Sealyham terrier, Sealyham",	"Airedale, Airedale terrier",	"cairn, cairn terrier",	"Australian terrier",	"Dandie Dinmont, Dandie Dinmont terrier",	"Boston bull, Boston terrier",	"miniature schnauzer",	"giant schnauzer",	"standard schnauzer",	"Scotch terrier, Scottish terrier, Scottie",	"Tibetan terrier, chrysanthemum dog",	"silky terrier, Sydney silky",	"soft-coated wheaten terrier",	"West Highland white terrier",	"Lhasa, Lhasa apso",	"flat-coated retriever",	"curly-coated retriever",	"golden retriever",	"Labrador retriever",	"Chesapeake Bay retriever",	"German short-haired pointer",	"vizsla, Hungarian pointer",	"English setter",	"Irish setter, red setter",	"Gordon setter",	"Brittany spaniel",	"clumber, clumber spaniel",	"English springer, English springer spaniel",	"Welsh springer spaniel",	"cocker spaniel, English cocker spaniel, cocker",	"Sussex spaniel",	"Irish water spaniel",	"kuvasz",	"schipperke",	"groenendael",	"malinois",	"briard",	"kelpie",	"komondor",	"Old English sheepdog, bobtail",	"Shetland sheepdog, Shetland sheep dog, Shetland",	"collie",	"Border collie",	"Bouvier des Flandres, Bouviers des Flandres",	"Rottweiler",	"German shepherd, German shepherd dog, German police dog, alsatian",	"Doberman, Doberman pinscher",	"miniature pinscher",	"Greater Swiss Mountain dog",	"Bernese mountain dog",	"Appenzeller",	"EntleBucher",	"boxer",	"bull mastiff",	"Tibetan mastiff",	"French bulldog",	"Great Dane",	"Saint Bernard, St Bernard",	"Eskimo dog, husky",	"malamute, malemute, Alaskan malamute",	"Siberian husky",	"dalmatian, coach dog, carriage dog",	"affenpinscher, monkey pinscher, monkey dog",	"basenji",	"pug, pug-dog",	"Leonberg",	"Newfoundland, Newfoundland dog",	"Great Pyrenees",	"Samoyed, Samoyede",	"Pomeranian",	"chow, chow chow",	"keeshond",	"Brabancon griffon",	"Pembroke, Pembroke Welsh corgi",	"Cardigan, Cardigan Welsh corgi",	"toy poodle",	"miniature poodle",	"standard poodle",	"Mexican hairless")
crostacei=c("Dungeness crab, Cancer magister",	"rock crab, Cancer irroratus",	"fiddler crab",	"king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica",	"American lobster, Northern lobster, Maine lobster, Homarus americanus",	"spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish",	"crayfish, crawfish, crawdad, crawdaddy",	"hermit crab",	"isopod")
edifici=c("barbershop",	"barn",	"bookshop, bookstore, bookstall",	"butcher shop, meat market",	"church, church building",	"cinema, movie theater, movie theatre, movie house, picture palace",	"greenhouse, nursery, glasshouse",	"grocery store, grocery, food market, market",	"lumbermill, sawmill",	"monastery",	"mosque",	"palace",	"prison, prison house",	"restaurant, eating house, eating place, eatery",	"shoe shop, shoe-shop, shoe store",	"tobacco shop, tobacconist shop, tobacconist",	"toyshop",	"yurt")
fauna=c("buckeye, horse chestnut, conker",	"sea anemone, anemone",	"rapeseed",	"daisy",	"yellow lady's slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum",	"hip, rose hip, rosehip",	"coral fungus",	"agaric",	"gyromitra",	"stinkhorn, carrion fungus",	"earthstar",	"hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa")
gatti=c("tabby, tabby cat",	"tiger cat",	"Persian cat",	"Siamese cat, Siamese",	"Egyptian cat")
imbarcazioni=c("aircraft carrier, carrier, flattop, attack aircraft carrier",	"boathouse",	"catamaran","container ship, containership, container vessel",	"fireboat",	"gondola",	"lifeboat",	"liner, ocean liner",	"paddlewheel, paddle wheel",	"schooner",	"speedboat",	"submarine, pigboat, sub, U-boat",	"trimaran",	"yawl")
insetti=c("tiger beetle",	"ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle",	"ground beetle, carabid beetle","centipede",	"long-horned beetle, longicorn, longicorn beetle",	"leaf beetle, chrysomelid",	"dung beetle",	"rhinoceros beetle",	"weevil",	"fly",	"bee",	"ant, emmet, pismire",	"grasshopper, hopper",	"cricket",	"walking stick, walkingstick, stick insect",	"cockroach, roach",	"mantis, mantid",	"cicada, cicala",	"leafhopper",	"lacewing, lacewing fly",	"dragonfly, darning needle, devil's darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk",	"damselfly",	"admiral",	"ringlet, ringlet butterfly",	"monarch, monarch butterfly, milkweed butterfly, Danaus plexippus",	"cabbage butterfly",	"sulphur butterfly, sulfur butterfly",	"lycaenid, lycaenid butterfly")
molluschi=c("flatworm, platyhelminth",	"nematode, nematode worm, roundworm",	"conch",	"snail",	"slug",	"sea slug, nudibranch",	"chiton, coat-of-mail shell, sea cradle, polyplacophore",	"chambered nautilus, pearly nautilus, nautilus",	"starfish, sea star",	"sea urchin",	"sea cucumber, holothurian")
mustelidi=c("weasel",	"mink",	"polecat, fitch, foulmart, foumart, Mustela putorius",	"black-footed ferret, ferret, Mustela nigripes",	"otter",	"skunk, polecat, wood pussy",	"badger",	"armadillo")
natura=c("spider web, spider's web",	"alp",	"bubble",	"cliff, drop, drop-off",	"coral reef",	"geyser",	"lakeside, lakeshore",	"promontory, headland, head, foreland",	"sandbar, sand bar",	"seashore, coast, seacoast, sea-coast",	"valley, vale",	"volcano")
oggetti_lavoro=c("apiary, bee house",	"abacus",	"ballpoint, ballpoint pen, ballpen, Biro",	"barber chair",	"barometer",	"barrel, cask",	"barrow, garden cart, lawn cart, wheelbarrow",	"binder, ring-binder",	"binoculars, field glasses, opera glasses",	"broom",	"bucket, pail",	"bulletproof vest",	"carpenter's kit, tool kit",	"carton",	"chain",	"chainlink fence",	"chain saw, chainsaw",	"cleaver, meat cleaver, chopper",	"coil, spiral, volute, whorl, helix",	"crane",	"forklift",	"fountain pen",	"freight car",	"gasmask, respirator, gas helmet",	"hammer",	"harvester, reaper",	"hatchet",	"iron, smoothing iron",	"knot",	"lab coat, laboratory coat",	"lawn mower, mower",	"loupe, jeweler's loupe",	"measuring cup",	"microphone, mike",	"mitten",	"paintbrush",	"pencil box, pencil case",	"pencil sharpener",	"Petri dish",	"plunger, plumber's helper",	"potter's wheel",	"power drill",	"quill, quill pen",	"rubber eraser, rubber, pencil eraser",	"rule, ruler",	"safety pin",	"scale, weighing machine",	"screw",	"screwdriver",	"sewing machine",	"shovel",	"slide rule, slipstick",	"spatula",	"spindle",	"stethoscope",	"stopwatch, stop watch",	"stretcher",	"thimble",	"torch",	"tripod",	"whistle")
ogetti_sociale=c("cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",	"combination lock",	"flagpole, flagstaff",	"gas pump, gasoline pump, petrol pump, island dispenser",	"jack-o'-lantern",	"manhole cover",	"maypole",	"padlock",	"parking meter",	"pay-phone, pay-station",	"planetarium",	"plastic bag",	"pole",	"sliding door",	"solar dish, solar collector, solar furnace",	"stone wall",	"throne",	"turnstile",	"vault",	"vending machine",	"street sign",	"traffic light, traffic signal, stoplight")
oggetti_casa=c("ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin","packet",	"bakery, bakeshop, bakehouse",	"bannister, banister, balustrade, balusters, handrail",	"bassinet",	"bassoon",	"bath towel",	"bathtub, bathing tub, bath, tub",	"beaker",	"bearskin, busby, shako",	"beer bottle",	"beer glass",	"bell cote, bell cot",	"birdhouse",	"bookcase",	"bottlecap",	"bow",	"caldron, cauldron",	"candle, taper, wax light",	"can opener, tin opener",	"chiffonier, commode",	"chime, bell, gong",	"china cabinet, china closet",	"Christmas stocking",	"cocktail shaker",	"coffee mug",	"coffeepot",	"corkscrew, bottle screw",	"cradle",	"crate",	"crib, cot",	"Crock Pot",	"desk",	"dial telephone, dial phone",	"dining table, board",	"dishrag, dishcloth",	"disk brake, disc brake",	"doormat, welcome mat",	"Dutch oven",	"entertainment center",	"envelope",	"espresso maker",	"file, file cabinet, filing cabinet",	"fire screen, fireguard",	"folding chair",	"four-poster",	"French horn, horn",	"frying pan, frypan, skillet",	"goblet",	"hamper",	"handkerchief, hankie, hanky, hankey",	"hourglass",	"ladle",	"lampshade, lamp shade",	"letter opener, paper knife, paperknife",	"mailbox, letter box",	"matchstick",	"microwave, microwave oven",	"mixing bowl",	"mortar",	"mosquito net",	"paper towel",	"park bench",	"picket fence, paling",	"piggy bank, penny bank",	"pillow",	"pitcher, ewer",	"plate rack",	"pot, flowerpot",	"prayer rug, prayer mat",	"quilt, comforter, comfort, puff",	"radiator",	"rain barrel",	"refrigerator, icebox",	"remote control, remote",	"rocking chair, rocker",	"rotisserie",	"safe",	"saltshaker, salt shaker",	"shoji",	"shower curtain",	"soap dispenser",	"soup bowl",	"space heater",	"stove",	"strainer",	"studio couch, day bed",	"table lamp",	"teapot",	"television, television system",	"toaster",	"toilet seat",	"tray",	"tub, vat",	"vacuum, vacuum cleaner",	"vase",	"waffle iron",	"wall clock",	"wardrobe, closet, press",	"washbasin, handbasin, washbowl, lavabo, wash-hand basin",	"washer, automatic washer, washing machine",	"water jug",	"window screen",	"window shade",	"wok",	"wooden spoon",	"plate",	"cup",	"toilet tissue, toilet paper, bathroom tissue")
oggetti_cura_persona=c("Band Aid",	"crutch",	"diaper, nappy, napkin",	"face powder",	"hair spray",	"lotion",	"medicine chest, medicine cabinet",	"neck brace",	"oxcart",	"oxygen mask",	"pill bottle",	"shower cap",	"sunscreen, sunblock, sun blocker",	"swab, swob, mop",	"syringe",	"umbrella")
oggetti_tecnologici=c("cassette",	"cassette player",	"CD player",	"cellular telephone, cellular phone, cellphone, cell, mobile phone",	"computer keyboard, keypad",	"desktop computer",	"dishwasher, dish washer, dishwashing machine",	"electric fan, blower",	"hand blower, blow dryer, blow drier, hair dryer, hair drier",	"hand-held computer, hand-held microcomputer",	"hard disc, hard disk, fixed disk",	"home theater, home theatre",	"laptop, laptop computer",	"loudspeaker, speaker, speaker unit, loudspeaker system, speaker system",	"modem",	"monitor",	"mouse, computer mouse",	"notebook, notebook computer",	"oscilloscope, scope, cathode-ray oscilloscope, CRO",	"photocopier",	"Polaroid camera, Polaroid Land camera",	"printer",	"projector",	"radio, wireless",	"radio telescope, radio reflector",	"reflex camera",	"screen, CRT screen",	"space bar",	"switch, electric switch, electrical switch",	"typewriter keyboard",	"web site, website, internet site, site")
oggetti_tempo_libero=c("muzzle","croquet ball",	"balance beam, beam",	"balloon",	"barbell",	"baseball",	"basketball",	"bobsled, bobsleigh, bob",	"canoe",	"carousel, carrousel, merry-go-round, roundabout, whirligig",	"dumbbell",	"football helmet",		"golf ball",		"hook, claw",	"horizontal bar, high bar",	"iPod",	"jigsaw puzzle",	"joystick",	"knee pad",	"lens cap, lens cover",	"magnetic compass",	"mountain tent",	"paddle, boat paddle",	"parachute, chute",	"parallel bars, bars",	"ping-pong ball",	"pinwheel",	"pool table, billiard table, snooker table",	"puck, hockey puck",	"punching bag, punch bag, punching ball, punchball",	"racket, racquet",	"rugby ball",	"scoreboard",	"shopping basket",	"shopping cart",	"ski",	"ski mask",	"sleeping bag",	"slot, one-armed bandit",	"snorkel",	"soccer ball",	"swing",	"tape player",	"teddy, teddy bear",	"tennis ball",	"theater curtain, theatre curtain",	"volleyball",	"comic book",	"crossword puzzle, crossword",	"book jacket, dust cover, dust jacket, dust wrapper",	"menu")
ominide_scimmia=c("orangutan, orang, orangutang, Pongo pygmaeus",	"gorilla, Gorilla gorilla",	"chimpanzee, chimp, Pan troglodytes",	"gibbon, Hylobates lar",	"siamang, Hylobates syndactylus, Symphalangus syndactylus",	"guenon, guenon monkey",	"patas, hussar monkey, Erythrocebus patas",	"baboon",	"macaque",	"langur",	"colobus, colobus monkey",	"proboscis monkey, Nasalis larvatus",	"marmoset",	"capuchin, ringtail, Cebus capucinus",	"howler monkey, howler",	"titi, titi monkey",	"spider monkey, Ateles geoffroyi",	"squirrel monkey, Saimiri sciureus")
parti_corpo=c("chest",	"nail",	"nipple",	"ear, spike, capitulum")
pesci=c("tench, Tinca tinca",	"goldfish, Carassius auratus",	"great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias",	"tiger shark, Galeocerdo cuvieri",	"hammerhead, hammerhead shark",	"electric ray, crampfish, numbfish, torpedo",	"stingray",	"grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus",	"killer whale, killer, orca, grampus, sea wolf, Orcinus orca",	"barracouta, snoek",	"eel",	"coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch",	"rock beauty, Holocanthus tricolor",	"anemone fish",	"sturgeon",	"gar, garfish, garpike, billfish, Lepisosteus osseus",	"lionfish",	"puffer, pufferfish, blowfish, globefish")
rettili=c("loggerhead, loggerhead turtle, Caretta caretta",	"leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea",	"mud turtle",	"terrapin",	"box turtle, box tortoise",	"banded gecko",	"common iguana, iguana, Iguana iguana",	"American chameleon, anole, Anolis carolinensis",	"whiptail, whiptail lizard",	"agama",	"frilled lizard, Chlamydosaurus kingi",	"alligator lizard",	"Gila monster, Heloderma suspectum",	"green lizard, Lacerta viridis",	"African chameleon, Chamaeleo chamaeleon",	"Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis",	"African crocodile, Nile crocodile, Crocodylus niloticus",	"American alligator, Alligator mississipiensis",	"thunder snake, worm snake, Carphophis amoenus",	"ringneck snake, ring-necked snake, ring snake",	"hognose snake, puff adder, sand viper",	"green snake, grass snake",	"king snake, kingsnake",	"garter snake, grass snake",	"water snake",	"vine snake",	"night snake, Hypsiglena torquata",	"boa constrictor, Constrictor constrictor",	"rock python, rock snake, Python sebae",	"Indian cobra, Naja naja",	"green mamba",	"sea snake",	"horned viper, cerastes, sand viper, horned asp, Cerastes cornutus",	"diamondback, diamondback rattlesnake, Crotalus adamanteus",	"sidewinder, horned rattlesnake, Crotalus cerastes")
roditori=c("hamster",	"porcupine, hedgehog",	"fox squirrel, eastern fox squirrel, Sciurus niger",	"marmot",	"beaver",	"guinea pig, Cavia cobaya")
strumenti_musicali=c("accordion, piano accordion, squeeze box",	"acoustic guitar",	"banjo",	"cello, violoncello",	"cornet, horn, trumpet, trump",	"drum, membranophone, tympan",	"electric guitar",	"flute, transverse flute",	"gong, tam-tam",	"grand piano, grand",	"harmonica, mouth organ, harp, mouth harp",	"harp",	"maraca",	"marimba, xylophone",	"oboe, hautboy, hautbois",	"ocarina, sweet potato",	"organ, pipe organ",	"panpipe, pandean pipe, syrinx",	"pick, plectrum, plectron",	"sax, saxophone",	"steel drum",	"trombone",	"upright, upright piano",	"violin, fiddle")
uccelli=c("cock",	"hen",	"ostrich, Struthio camelus",	"brambling, Fringilla montifringilla",	"goldfinch, Carduelis carduelis",	"house finch, linnet, Carpodacus mexicanus",	"junco, snowbird",	"indigo bunting, indigo finch, indigo bird, Passerina cyanea",	"robin, American robin, Turdus migratorius",	"bulbul",	"jay",	"magpie",	"chickadee",	"water ouzel, dipper",	"kite",	"bald eagle, American eagle, Haliaeetus leucocephalus",	"vulture",	"great grey owl, great gray owl, Strix nebulosa",	"black grouse",	"ptarmigan",	"ruffed grouse, partridge, Bonasa umbellus",	"prairie chicken, prairie grouse, prairie fowl",	"peacock",	"quail",	"partridge",	"African grey, African gray, Psittacus erithacus",	"macaw",	"sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita",	"lorikeet",	"coucal",	"bee eater",	"hornbill",	"hummingbird",	"jacamar",	"toucan",	"drake",	"red-breasted merganser, Mergus serrator",	"goose",	"black swan, Cygnus atratus",	"white stork, Ciconia ciconia",	"black stork, Ciconia nigra",	"spoonbill",	"flamingo",	"little blue heron, Egretta caerulea",	"American egret, great white heron, Egretta albus",	"bittern",	"crane",	"limpkin, Aramus pictus",	"European gallinule, Porphyrio porphyrio",	"American coot, marsh hen, mud hen, water hen, Fulica americana",	"bustard",	"ruddy turnstone, Arenaria interpres",	"red-backed sandpiper, dunlin, Erolia alpina",	"redshank, Tringa totanus",	"dowitcher",	"oystercatcher, oyster catcher",	"pelican",	"king penguin, Aptenodytes patagonica",	"albatross, mollymawk")
veicoli=c("ambulance",	"amphibian, amphibious vehicle",	"bicycle-built-for-two, tandem bicycle, tandem","beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon",	"cab, hack, taxi, taxicab",	"convertible",	"dogsled, dog sled, dog sleigh",	"electric locomotive",	"fire engine, fire truck",	"garbage truck, dustcart","go-kart", "golfcart, golf cart",	"half track",	"horse cart, horse-cart",	"jeep, landrover",	"jinrikisha, ricksha, rickshaw",	"limousine, limo",	"minibus",	"minivan",	"Model T",	"moped",	"motor scooter, scooter",	"mountain bike, all-terrain bike, off-roader",	"moving van",	"passenger car, coach, carriage",	"pickup, pickup truck",	"plow, plough",	"police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria",	"racer, race car, racing car",	"recreational vehicle, RV, R.V.",	"school bus",	"snowmobile",	"snowplow, snowplough",	"sports car, sport car",	"steam locomotive",	"streetcar, tram, tramcar, trolley, trolley car",	"thresher, thrasher, threshing machine",	"tow truck, tow car, wrecker",	"tractor",	"trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi",	"tricycle, trike, velocipede",	"trolleybus, trolley coach, trackless trolley",	"unicycle, monocycle")

full_path=vector()
file_list=list()
i=0

for ( f in file_names){
  i=i+1
  full_path[i]=file.path(path,f)
  file_list[[i]]=read.delim(full_path[i],header=F)
  #file_list[[1]][1:5,]
  #file_list[[42]][1:5,]
}
  
#replacing labels
for ( j in 1:43){
  file_list[[j]]$V4<-ifelse(file_list[[j]]$V2 %in% abbigliamento,"abbigliamento",
                     ifelse(file_list[[j]]$V2 %in% accessori_veicoli,"accessori_veicoli",
                     ifelse(file_list[[j]]$V2 %in% accessori_persona,"accessori_persona",
                     ifelse(file_list[[j]]$V2 %in% aerei,"aerei",
                     ifelse(file_list[[j]]$V2 %in% alimenti,"alimenti",
                     ifelse(file_list[[j]]$V2 %in% altro,"altro",      
                     ifelse(file_list[[j]]$V2 %in% anfibi,"anfibi",
                     ifelse(file_list[[j]]$V2 %in% animali_estinti,"animali_estinti",
                     ifelse(file_list[[j]]$V2 %in% animali_marini,"animali_marini",
                     ifelse(file_list[[j]]$V2 %in% animali_selvatici,"animali_selvatici",
                     ifelse(file_list[[j]]$V2 %in% aracnidi,"aracnidi",
                     ifelse(file_list[[j]]$V2 %in% architetture,"architetture",
                     ifelse(file_list[[j]]$V2 %in% armi,"armi",
                     ifelse(file_list[[j]]$V2 %in% bevande,"bevande",
                     ifelse(file_list[[j]]$V2 %in% bovini,"bovini",
                     ifelse(file_list[[j]]$V2 %in% cani, "cani",
                     ifelse(file_list[[j]]$V2 %in% crostacei, "crostacei",
                     ifelse(file_list[[j]]$V2 %in% edifici, "edifici",
                     ifelse(file_list[[j]]$V2 %in% fauna, "fauna",
                     ifelse(file_list[[j]]$V2 %in% gatti, "gatti",
                     ifelse(file_list[[j]]$V2 %in% imbarcazioni, "imbarcazioni",
                     ifelse(file_list[[j]]$V2 %in% insetti, "insetti",
                     ifelse(file_list[[j]]$V2 %in% molluschi, "molluschi",
                     ifelse(file_list[[j]]$V2 %in% mustelidi, "mustelidi",
                     ifelse(file_list[[j]]$V2 %in% natura, "natura",
                     ifelse(file_list[[j]]$V2 %in% oggetti_lavoro, "oggetti_lavoro",
                     ifelse(file_list[[j]]$V2 %in% ogetti_sociale, "ogetti_sociale",
                     ifelse(file_list[[j]]$V2 %in% oggetti_casa, "oggetti_casa",
                     ifelse(file_list[[j]]$V2 %in% oggetti_cura_persona, "oggetti_cura_persona",
                     ifelse(file_list[[j]]$V2 %in% oggetti_tecnologici, "oggetti_tecnologici",
                     ifelse(file_list[[j]]$V2 %in% oggetti_tempo_libero, "oggetti_tempo_libero",
                     ifelse(file_list[[j]]$V2 %in% ominide_scimmia, "ominide_scimmia",
                     ifelse(file_list[[j]]$V2 %in% parti_corpo, "parti_corpo",
                     ifelse(file_list[[j]]$V2 %in% persone, "persone",
                     ifelse(file_list[[j]]$V2 %in% pesci, "pesci",
                     ifelse(file_list[[j]]$V2 %in% rettili, "rettili",
                     ifelse(file_list[[j]]$V2 %in% roditori, "roditori",
                     ifelse(file_list[[j]]$V2 %in% strumenti_musicali, "strumenti_musicali",
                     ifelse(file_list[[j]]$V2 %in% uccelli, "uccelli",
                     ifelse(file_list[[j]]$V2 %in% veicoli, "veicoli","nulla" 
                     ))))))))))))))))))))))))))))))))))))))))}

Mode = function(x){ 
  ta = table(x)
  tam = max(ta)
  if (all(ta == tam))
    mod = NA
  else
    if(is.numeric(x))
      mod = as.numeric(names(ta)[ta == tam])
  else
    mod = names(ta)[ta == tam]
  return(mod)
}    

file_list_a=as.matrix(file_list)

file_list_03=list()
j=0

for (i in 1:43){
  j=j+1
  file_list_03[[j]]=file_list_a[[i]][which(file_list_a[[i]]$V3>=0.3),]
}

moda=vector()
j=0

for (i in 1:43){
  j=j+1
  moda[j]=Mode(file_list[[j]]$V4)
}

moda
moda1=data.frame(moda)
moda1$paese_iso=c("ao","sa","ar","au","be","br","ca","cl","co","kp","ec","eg","fj","ph","fr","de","jp","in",
              "id","ie","it","ma","mx","ng","no","nz","nl","pk","pg","pe","gb","ru","ws","sn","es",
              "us","se","tz","th","to","tr","ug","ve")
write.csv(moda1,"moda_finale.csv")


